baseurl = "http://harsanyisportpszichologus.hu"
title = "Dr. Harsányi Szabolcs Gergő (PhD)"
theme = "dimension"
languageCode = "hu-hu"
defaultContentLanguage = "hu"
enableRobotsTXT = true
disableRSS = true
googleAnalytics = "UA-103438479-1"

[params]
  title = "Dr. Harsányi Szabolcs Gergő (PhD)"
  description = '<!--[--> <b> Sportpszichológus (sport szakpszichológus) egyetemi adjunktus, pszichológus </b> <!--]--><br />
                 <!--[--> <b> E-mail:</b> tudommar@gmail.com<!--]--> <br />
                 <!--[--> <b>Tartózkodási hely:</b>Budapest / Szeged<!--]-->'
                
  logo = "fa-graduation-cap"
  copyright = "Untitled"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"

[languages]
[languages.hu]
languageName = "Magyar"
weight = 1
title = "Dr. Harsányi Szabolcs Gergő (PhD)"

